/**
 * Conversations API client.
 * Uses apiClient which points to backend (direct or via Next.js proxy).
 */

import { saveAs } from "file-saver";
import { apiClient } from "@/lib/api-client";
import type { ChatMessage, ToolCall } from "@/types";

export interface ConversationResponse {
  id: string;
  user_id: string;
  title: string | null;
  created_at: string;
  updated_at: string | null;
  viz_count?: number;
  csv_filename?: string | null;
}

export interface VisualizationItem {
  task_id: string;
  chart_type: string;
  features: string[];
  status: string;
  image_url: string | null;
  /** Includes critic fields when present: critic_reason, failure_type, action, skip_kind, replacement_requested, critic_attempts */
  metadata: Record<string, unknown> | null;
  annotation: string | null;
  created_at: string | null;
  /** True when generated by the chat assistant (generate_visualizations tool). */
  is_chat_viz: boolean;
}

export interface CsvSummaryShape {
  column_types: Record<string, string>;
  sample_rows: string;
  /** Structured sample data for table display (avoids parsing sample_rows). */
  sample_data?: Array<Record<string, string | number | boolean | null>>;
  row_count: number;
  column_count: number;
  error?: string | null;
  missing_values_by_column?: Record<string, number>;
  missing_values_handled?: string;
  duplicate_rows_removed?: number;
  row_count_before_cleaning?: number;
}

export interface CsvContextResponse {
  csv_summary: CsvSummaryShape;
  /** Original CSV (for Data Upload). */
  original_csv_summary?: CsvSummaryShape | null;
}

/** Detail with optional visualization refs (1-indexed). */
export type ReportDetail = { text: string; viz_refs?: number[] };

export interface ReportResponse {
  dataset_overview: string;
  key_findings: Array<{
    theme: string;
    summary: string;
    details?: ReportDetail[];
  }>;
  relationship_analysis: Array<{
    variables: string[];
    description: string;
  }>;
  suggestions: string[];
}

export interface ChatMessageResponse {
  id: string;
  conversation_id: string;
  role: string;
  content: string;
  tool_calls: Array<{
    id: string;
    name: string;
    args: Record<string, unknown>;
    result?: unknown;
    status: string;
  }> | null;
  is_streaming: boolean;
  group_id: string | null;
  csv_filename?: string | null;
  csv_content?: string | null;
  created_at: string;
  updated_at: string | null;
  timestamp: string;
}

export interface ConversationWithMessagesResponse extends ConversationResponse {
  messages: ChatMessageResponse[];
}

function toChatMessage(r: ChatMessageResponse): ChatMessage {
  return {
    id: r.id,
    role: r.role as ChatMessage["role"],
    content: r.content,
    timestamp: new Date(r.timestamp || r.created_at),
    toolCalls: r.tool_calls?.map((tc) => ({
      id: tc.id,
      name: tc.name,
      args: tc.args,
      result: tc.result,
      status: tc.status as ToolCall["status"],
    })),
    isStreaming: r.is_streaming,
    groupId: r.group_id ?? undefined,
  };
}

export const conversationsApi = {
  async list(): Promise<ConversationResponse[]> {
    return apiClient.get<ConversationResponse[]>("/conversations");
  },

  async create(title?: string | null): Promise<ConversationResponse> {
    return apiClient.post<ConversationResponse>("/conversations", { title: title ?? null });
  },

  async get(id: string): Promise<ConversationWithMessagesResponse> {
    return apiClient.get<ConversationWithMessagesResponse>(`/conversations/${id}`);
  },

  async update(id: string, data: { title?: string }): Promise<ConversationResponse> {
    return apiClient.patch<ConversationResponse>(`/conversations/${id}`, data);
  },

  async delete(id: string): Promise<void> {
    return apiClient.delete(`/conversations/${id}`);
  },

  async addMessage(
    conversationId: string,
    data: {
      role: string;
      content?: string;
      tool_calls?: Array<{
        id: string;
        name: string;
        args: Record<string, unknown>;
        result?: unknown;
        status: string;
      }>;
      is_streaming?: boolean;
      group_id?: string | null;
    }
  ): Promise<ChatMessageResponse> {
    return apiClient.post<ChatMessageResponse>(`/conversations/${conversationId}/messages`, {
      role: data.role,
      content: data.content ?? "",
      tool_calls: data.tool_calls ?? null,
      is_streaming: data.is_streaming ?? false,
      group_id: data.group_id ?? null,
    });
  },

  /** Add a message with an attached CSV/JSON file (multipart upload). */
  async addMessageWithCsv(
    conversationId: string,
    content: string,
    file: File,
    role = "user"
  ): Promise<ChatMessageResponse> {
    const formData = new FormData();
    formData.append("content", content);
    formData.append("role", role);
    formData.append("file", file);
    return apiClient.postMultipart<ChatMessageResponse>(
      `/conversations/${conversationId}/messages/with-csv`,
      formData
    );
  },

  /** Add a message by fetching public JSON from URL server-side. */
  async addMessageWithUrl(
    conversationId: string,
    content: string,
    url: string,
    role = "user"
  ): Promise<ChatMessageResponse> {
    return apiClient.post<ChatMessageResponse>(
      `/conversations/${conversationId}/messages/with-url`,
      {
        content,
        role,
        url,
      }
    );
  },

  async updateMessage(
    conversationId: string,
    messageId: string,
    data: {
      content?: string;
      tool_calls?: Array<{
        id: string;
        name: string;
        args: Record<string, unknown>;
        result?: unknown;
        status: string;
      }>;
      is_streaming?: boolean;
    }
  ): Promise<ChatMessageResponse> {
    return apiClient.patch<ChatMessageResponse>(
      `/conversations/${conversationId}/messages/${messageId}`,
      data
    );
  },

  async clearMessages(conversationId: string): Promise<void> {
    return apiClient.delete(`/conversations/${conversationId}/messages`);
  },

  async listVisualizations(conversationId: string): Promise<VisualizationItem[]> {
    return apiClient.get<VisualizationItem[]>(`/conversations/${conversationId}/visualizations`);
  },

  /**
   * Generate 10 more visualizations for a conversation.
   * Streams progress via SSE. Calls onEvent(eventType, data) for each event.
   * Passes user's OpenRouter config from localStorage when available.
   */
  async generateMoreVisualizations(
    conversationId: string,
    onEvent: (eventType: string, data: unknown) => void | Promise<void>
  ): Promise<void> {
    const body: Record<string, string> = {};
    if (typeof window !== "undefined") {
      const apiKey = localStorage.getItem("openrouter_api_key");
      const model = localStorage.getItem("ai_model") || "anthropic/claude-3.5-sonnet";
      if (apiKey) {
        body.openrouter_api_key = apiKey;
        body.ai_model = model;
      }
    }
    return apiClient.postSSE(
      `/conversations/${conversationId}/generate-more-visualizations`,
      onEvent,
      Object.keys(body).length > 0 ? body : undefined
    );
  },

  async getCsvContext(conversationId: string): Promise<CsvContextResponse> {
    return apiClient.get<CsvContextResponse>(`/conversations/${conversationId}/csv-context`);
  },

  async getReport(conversationId: string): Promise<ReportResponse> {
    return apiClient.get<ReportResponse>(`/conversations/${conversationId}/report`);
  },

  async generateReport(conversationId: string, language = "en"): Promise<ReportResponse> {
    return apiClient.post<ReportResponse>(
      `/conversations/${conversationId}/report?language=${language}`
    );
  },

  /**
   * Export report with embedded images (PDF, DOCX, MD).
   * Triggers file download. Uses backend for proper image embedding.
   */
  async exportReport(conversationId: string, format: "pdf" | "docx" | "md"): Promise<void> {
    const blob = await apiClient.getBlob(`/conversations/${conversationId}/report/export`, {
      format,
    });
    saveAs(blob, `insights-summary.${format}`);
  },

  toChatMessage,
};
